#!/bin/sh /etc/rc.common
SCRIPT_NAME="Traffic Monitor"
SCRIPT_PATH="/root/traffic_monitor.sh"
LOG_FILE="/tmp/traffic_monitor.log"
START=99
STOP=99
start() {       
        echo "Starting $SCRIPT_NAME"
        $SCRIPT_PATH >> $LOG_FILE 2>&1 &
}                
stop() {         
        echo "Stopping $SCRIPT_NAME"
	    kill $(cat /tmp/traffic_monitor.lock)
		rm /tmp/traffic_monitor.lock
}

